services:
  front:
    build:
      context: ./cmd/frontend
      dockerfile: DockerFile
    container_name: front
    restart: unless-stopped
    expose:
      - "3000"  # Porta usada internamente pelo Caddy
    environment:
      - NODE_ENV=production

  
  views:
    build:
      context: ./cmd/views
      dockerfile: Dockerfile
    container_name: views
    restart: unless-stopped
    expose:
      - "1234"  # Porta usada internamente entre containers

    # ✅ Mapeamento da porta para acesso externo ao backend
    ports:
      - "1234:1234"

  caddy:
    image: mirror.gcr.io/library/caddy:2.8
    container_name: caddy
    restart: unless-stopped
    ports:
      - "80:80"  # Acesso HTTP externo
      # - "443:443" # (Descomente se for usar HTTPS/TLS)
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile:ro  # Caddyfile de configuração
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - front
      - views

volumes:
  caddy_data:
  caddy_config:
